spring:
  datasource:
    url: jdbc:h2:./db/sample
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # JPA 에서 ddl 삭제 및 생성
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
