spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
